services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-service
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - ./backend/.env
    environment:
      - DATABASE_URL=${DATABASE_URL_DEV}
      - JWT_SECRET_KEY={SECRET_KEY}
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend/finance-tracker
      dockerfile: Dockerfile
    container_name: frontend-service
    ports:
      - "3000:80"
    depends_on:
      - backend
    env_file:
      - ./frontend/finance-tracker/.env.${NODE_ENV}
    environment:
      - VITE_API_URL=${VITE_API_URL}

  db:
    image: postgres:16
    restart: always
    env_file:
      - ./backend/.env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
