apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
      - name: backend-service
        image: kevxo09/finance-tracker-backend:latest
        ports:
        - containerPort: 8000
        env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: backend-secrets
                key: database_url
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: backend-secrets
                key: jwt_secret
