apiVersion: apps/v1
kind: Deployment
metadata:
  name: finance-tracker-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: finance-tracker-db
  template:
    metadata:
      labels:
        app: finance-tracker-db
    spec:
      containers:
      - name: postgres
        image: postgres:16
        ports:
          - containerPort: 5432
        env:
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: db-config
                key: POSTGRES_DB
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: db-config
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: POSTGRES_PASSWORD
        volumeMounts:
          - name: postgres-storage
            mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
