apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: finance-tracker
spec:
  type: ClusterIP
  selector:
    app: fincance-tracker-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
