apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend-service
        image: finance-tracker-frontend
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: my-registry-secret
