"""create user, expense and budget tables

Revision ID: 891d711d6a5e
Revises:
Create Date: 2024-09-27 17:09:47.549267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "891d711d6a5e"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(op.f("ix_user_username"), "user", ["username"], unique=True)
    op.create_index(op.f("ix_user_uuid"), "user", ["uuid"], unique=False)
    op.create_table(
        "budget",
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.Column("user_uuid", sa.String(), nullable=True),
        sa.Column("budget_amount", sa.Float(), nullable=False),
        sa.Column("month", sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_uuid"],
            ["user.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(op.f("ix_budget_uuid"), "budget", ["uuid"], unique=False)
    op.create_table(
        "expense",
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.Column("user_uuid", sa.String(), nullable=True),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("category", sa.String(), nullable=True),
        sa.Column("date", sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_uuid"],
            ["user.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(op.f("ix_expense_category"), "expense", ["category"], unique=False)
    op.create_index(op.f("ix_expense_uuid"), "expense", ["uuid"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_expense_uuid"), table_name="expense")
    op.drop_index(op.f("ix_expense_category"), table_name="expense")
    op.drop_table("expense")
    op.drop_index(op.f("ix_budget_uuid"), table_name="budget")
    op.drop_table("budget")
    op.drop_index(op.f("ix_user_uuid"), table_name="user")
    op.drop_index(op.f("ix_user_username"), table_name="user")
    op.drop_table("user")
    # ### end Alembic commands ###
